### ISSUE TITLE
As a developer, I want to be able to test all authentication flows locally

### ISSUE THREAD

**Issue by carlsonem** [18F/fs-open-forest-platform#619] opened 2019-04-29 15:33 UTC
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [ ]

## Tasks
- [ ] 
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by davemcorwin** [comment] 2019-04-29 17:38
@carlsonem is this a dupe of #613?

**Comment by carlsonem** [comment] 2019-06-10 17:58
Confirmed duplicate

**Closed** 2019-06-12 17:06 UTC
